### ISSUE TITLE
Try Semantic Specifications

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/jsmith#93]
I have already describe this approach [there](). Thus, just repeat it here. We might try to guide the random program generation process by using special semantic  files that would alter the generation output based on the logic written in them.

```yaml
- name: VariableDeclaration
  match:
    rule: stat
    for:
      - name: ID
  action: declare_variable

- name: VariableUsage
  match:
    rule: expr
    for:
      - name: ID
  action: use_variable
```
It's just an example. You free to use any format you want.
